### ISSUE TITLE
project with no index.html doesn't add app component

### ISSUE THREAD

**Issue by netanelgilad** [Urigo/Meteor-Angular2#35]
I am currently going through the tutorial and I can't get it to work without the index.html. If I have an index.html file with:
```
<body>
  <app></app>
</body>
```
everything works fine. But when I remove the index.html I get errors about finding the app selector (it is indeed cannot be found in the create html.
I don't have any other html files in my project. A reproduction can be found [here](https://github.com/netanelgilad/angular2-index-bug).

**Comment by barbatus** [comment]
Yes, I am familiar with that issue (i.e. [here](https://github.com/barbatus/ng2-compilers/blob/master/compilers/html_compiler.js#L36)). I didn't find any way to add bootstrap html if an app has no html at all.

A fix would be to add an empty html file to the current package. Adding bootstrap content to some html file in this package  (say, default_layout.html) I considered worse since it would require a hardcoded check that file comes from the package and has a specific name.

**Comment by Urigo** [comment]
@netanelgilad why would you want the app to work without any HTML files?

**Comment by netanelgilad** [comment]
It's not that I want an app without any HTML files, I don't want the index.html file specifically, since it is just boilerplate if you follow the best practices of the tutorial.
![image](https://cloud.githubusercontent.com/assets/3474905/12710074/3eb2ae2c-c8bb-11e5-8713-cfde339fa0fd.png)

**Comment by Urigo** [comment]
@netanelgilad ohh you mean it has a restriction for the specific `index.html` name?
